
PREP(addToCurators);
PREP(ambientDoors);
PREP(canUseAddonVersion);
PREP(createExampleMarker);
PREP(findAverage);
PREP(findMatch);
PREP(findParamArray);
PREP(getfullMoonDates);
PREP(getParamArray);
PREP(getPosASL);
PREP(getPosATL);
PREP(getPylonsAvailable);
PREP(getRandPos);
PREP(getRandPosMarker);
PREP(getSunAngle);
PREP(getVersionAddon);
PREP(getVersionFramework);
PREP(hint);
PREP(isBlacklisted);
//PREP(isDebugConsoleAllowed); // CfgFunction
PREP(isDevBuild);
PREP(isNight);
PREP(isNightSoon);
PREP(setEditor);
PREP(setFramework);
PREP(setHideTerrainObjects);
PREP(setName);
//PREP(setTimeBySunAngle);
