#define COMPONENT 3den
#include "\x\gw\addons\main\script_mod.hpp"

//#define DEBUG_ENABLED_3DEN

#ifdef DEBUG_ENABLED_3DEN
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_3DEN
    #define DEBUG_SETTINGS DEBUG_SETTINGS_3DEN
#endif

#include "\x\gw\addons\main\script_macros.hpp"
#include "\a3\3DEN\UI\dikCodes.inc"

#define HIDEOBJECTFILTER ["BUILDING","HOUSE","CHURCH","CHAPEL","FUELSTATION","HOSPITAL","RUIN","BUNKER","TREE","SMALL TREE","BUSH","WALL","FENCE","BUSSTOP","CROSS","FOREST BORDER","FOREST SQUARE","FOREST TRIANGLE","FOREST","FORTRESS","FOUNTAIN","HIDE","LIGHTHOUSE","MAIN ROAD","POWER LINES","POWERSOLAR","POWERWAVE","POWERWIND","QUAY","RAILWAY","ROAD","ROCK","ROCKS","SHIPWRECK","STACK","TOURISM","TRACK","TRAIL","TRANSMITTER","VIEW-TOWER","WATERTOWER"]
